### PR TITLE
Fix texture API and opengl3 backend

### PR DESCRIPTION
**Pull request by iacore**

### CODE REVIEW

**Comment by dumheter** [comment]
Hey,

Similar to the other PR, I can't accept the dear imgui submodule version bump due to `ImageButtonEx` being changed/removed, which I use and dont want to fix.

Also, this change removes my extension header which I do use, so please revert that too.

Or take a look at michal-z's more feature complete dear imgui bindings library: https://github.com/michal-z/zig-gamedev/tree/main/libs/zgui

**Comment by iacore** [comment]
I think ImageButtonEx is still there, but now it's defined in `imgui.h`

**Comment by dumheter** [comment]
I'll merge this and fix my comments myself. Thanks for the PR.

**Comment by iacore** [comment]
It's un-fixed https://github.com/dumheter/zimgui/blob/main/src/zimgui.cpp#L150


Replace this line with
```
return ImGui::ImageButtonEx(im_id, texture_id, {x, y}, {uv0x, uv0y}, {uv1x, uv1y}, {0, 0, 0, 0}, {1, 1, 1, 1}, {});
```
and you are good

**Pull request merged**
